### ISSUE TITLE
Enter "Age at Case Filing" in missing cells

### ISSUE THREAD

**Issue by MsPockets** [codeforboston/clean-slate-data#146]
Suffolk county has missing data for "Age at Case Filing" that needs to be entered. 
Also any data that we can discern from the other data would be beneficial and I think we should so that if possible.

**Comment by linnal86** [comment]
@JoelTennyson - What are the next steps for adding "age at case filing" ?

**Comment by linnal86** [comment]
Closing in favor of #174
