### ISSUE TITLE
Recreate expungement flow 

### ISSUE THREAD

**Issue by srsexton94** [codeforboston/clean-slate-data#147]
Recreate a more visible/compiled graphic for the expungement flow - currently [here](https://docs.google.com/document/d/1fhfaA9VS6PGVBDsw1AkWDssKUPEmTpgVbV4JnqQo4eA/edit)

**Comment by jeremylang** [comment]
https://docs.google.com/document/d/1fhfaA9VS6PGVBDsw1AkWDssKUPEmTpgVbV4JnqQo4eA/edit

**Comment by sgalletta213** [comment]
Just finished creating a proofreading the expungement workflow: https://www.figma.com/file/SKe1PD91f22uI847hc2WZ1/Expungment-Flow?node-id=0%3A1

**Comment by actsao** [comment]
Expungement flow logic for now: [https://drive.google.com/drive/folders/11Vz3-2R5ry4QOxrn-Qb8kAQQnHnXUN78](https://drive.google.com/drive/folders/11Vz3-2R5ry4QOxrn-Qb8kAQQnHnXUN78)

**Comment by linnal86** [comment]
This is an outdated issue, @actsao posted new expungement flow above. Closing this issue.
