### ISSUE TITLE
Age data in Suffolk: Decide whether and how to approximate this

### ISSUE THREAD

**Issue by laurafeeney** [codeforboston/clean-slate-data#174]
There is no indicator of age for the Suffolk data: we do not have age, birth date, or an indication of whether a case was brought to juvenile court. Expungement is only available for offenses committed by those under 21 at the time of the offense. We think this data set should include minors, since there are dispositions like “delinquent” that are used for juveniles, and offenses include “possession of alcohol by a minor”. 

- Is this worth approximating, given that any approximation would be rough? Are rough proportions worth it? 

Things that won't work:

- **Juvenile vs adult court**. Suffolk only has one solely dedicated to juvenile cases-the Boston Juvenile Court. This court does not appear in our data set. Other cases are heard at the regular courts in special sessions. Our data only shows a 3-character abbreviation for the court; there is no designation indicating juvenile sessions. [Suffolk website for documentation](https://www.suffolkdistrictattorney.com/about-the-office/bureaus-of-the-suffolk-das-office) 

Other options:
- **Compute a proportion of the offenders likely to be juvenile, and likely to be eligible for expungement, based on NW data**. This hinges on NW and Suffolk being similar in underlying demographics and in the distributions of types of offenses charged and ages of alleged offenders. 
-- we can look for demographic data outside of the court system. and we can look at distribution of types of offenses.
- **Use disposition to indicate age**. This limits us to cases with a disposition that includes "delinquent" or other indicators of juvenile. Does this apply for all relevant juvenile cases? is it *always* the case that juvenile offenses are “delinquent/not delinquent” while adults are “guilty/not guilty”? Could use this to proxy -- especially if cfjj is interested mostly in cases that have an ‘actual’ or ‘final’ disposition 
- **Machine learning approach** Could train on NW data. Test on Middlesex, which doesn't have exact age but includes juvenile courts. See how predictive ML seems to be. Not sure we have enough data to make good approximations within the NW dataset, or if patterns of offenses or %s of juveniles are similar enough across districts, etc.

**Comment by laurafeeney** [comment]
#178  and #179 should help answer this

**Comment by linnalihe** [comment]
Closing issue for now because we don't have a good way to get / approximate this information.
We cannot determine age if data is not for only persons under 21.
