### ISSUE TITLE
Discuss questions to ask about 1000 persons court data from Paper Prisons

### ISSUE THREAD

**Issue by linnalihe** [codeforboston/clean-slate-data#200]
Paper Prisons has offered to provide court records for 1000 people in MA
What questions do we need to ask to understand whether this data will be useful for Clean Slate Data?

1. Does it have all the fields we need in order to determine current disqualification: (fields)
   - age of person at time of conviction?/arrest?
   - number of incidents / offense / charges (need to clarify terminology) within a court hearing
   - disposition
   - offense type
   - charge code
   - charge description
   - others?
   
2. Does it have juvenile record data?
3. How far back does this data go?
     
This is better than the DA data if it contains the whole record for each person.

**Comment by katebailey1230** [comment]
We sent the email with those questions and those answers will be forthcoming closer to the Hackathon.
