### ISSUE TITLE
Plan and run workshop for python pandas

### ISSUE THREAD

**Issue by linnalihe** [codeforboston/clean-slate-data#203]
Outline a short tutorial on how to use python pandas in jupyter notebook with the available datasets.

Linna:
- installing / setting up jupyter notebooks
- importing data

Matt:
- dataframes
- filtering, selecting, renaming, dropping null, and graphing

Linna:
brief overview of how categorizeCharge notebook was processing dataset
talk about naming conventions
provide resources for further learning

Run live session and record + summary in google docs. 
Date - tentative Thursday next week?

WORKSHOP COMPLETED: 8/23/21
Slides and Video in drive folder
https://drive.google.com/drive/u/0/folders/1ehYXJU3OKr8wQV471wpcX08a-EaC2IVu

**Comment by mknotts623** [comment]
I made a Jupyter notebook for the workshop, but I don't know how you wanted me to share it. I figured it was easiest just to share a Google Drive link and we can talk about where to officially put it later. Here it is in case you want to look it over: https://drive.google.com/drive/folders/12SO8KEZ_xZGI7xXf8eERmtB-fuzvye8B?usp=sharing

**Comment by linnalihe** [comment]
Hi Matt,

I tried to access the drive but you haven't made it public so I can't
access it. Are we keeping it private, if so I can request permission. Let
me know.

Thanks,
Linna

**Comment by mknotts623** [comment]
Sorry, I just didn't change the sharing permission, you should be able to view it now.
