### ISSUE TITLE
Move Google Drive content into Github

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate-data#34]
For issue #29 and proposal https://docs.google.com/document/d/1VQoCXcJNyfSx7eEVI7U4VrxPHAlIBWnIbJ2gFswa9Rc/edit?usp=sharing , I wrote plans for where and how google drive content would be migrated. I then proceeded to not do it. This issue can be closed once google drive content has been moved.

**Comment by linnal86** [comment]
This an older issue that has been discussed and no longer relevant. Closing.
