### ISSUE TITLE
Remove notebooks folder and move pieces to `analyses`

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate-data#48]
In line with changes to our [repo organization decision](https://docs.google.com/document/d/1VQoCXcJNyfSx7eEVI7U4VrxPHAlIBWnIbJ2gFswa9Rc/edit?usp=sharing), we're going to collapse the notebooks folder into analyses, and collapse that readme into the main folder one as well. Note that this link won't be the source of truth for long once Dawn moves the decision to the wiki.

**Comment by linnal86** [comment]
This is outdated, we are following a different directory organization pattern.
