### ISSUE TITLE
Docs: Contribution links lead to docs that need permissions

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate-data#57]
On https://github.com/codeforboston/clean-slate/wiki/Contributing, these links lead to docs that need permissions:
1. [Clean Slate Project Overview](https://docs.google.com/document/d/1RgdgMR6-YVQt7zPbDtKI090_BOEG14Y2LO-jClBC1Kk/edit)
1. [Write down your questions about our project](https://docs.google.com/document/d/1WJGJijM3Fts1RtnKGQSn0tZ82TL4nqU9VRAhhkXyi4Q/edit)

**Comment by knod** [comment]
Also, 'shared doc' (for new member questions) link on https://github.com/codeforboston/clean-slate/wiki/How-We-Do-Things that leads to https://docs.google.com/document/d/1WJGJijM3Fts1RtnKGQSn0tZ82TL4nqU9VRAhhkXyi4Q/edit.

**Comment by mikemahoney218** [comment]
Mentioned on #55, but I don't have access either -- did the folder get deleted or something? Think the original owner is needed here.

**Comment by knod** [comment]
Since we don't know what doc it is, I don't know how we'd find out who the owner is...

**Comment by knod** [comment]
Yeah, #55 might be the same link on a different wiki page.

**Comment by knod** [comment]
From what I can tell, these are working too now! Huzzah!

**Comment by linnal86** [comment]
Docs have been tested and are now accessible. Closing this issue.
